name: ${project.artifactId}
main: ${project.groupId}.kingdoms.warlords.${project.artifactId}
version: ${project.version}
author: Dallen/Donovan Allen
depend: [Citizens, ProtocolLib, BarAPI, KingdomsUtilities, KingdomsCore]