servers:
    - "Creative"
    - "Skywars"
    - "Factions"
    - "Prison"
    - "Prison2"
    - "Skyblock"
    - "Yellow"
    - "Yellow2"
    - "Red"
    - "Ancient"
    - "Iceage"
    - "Hub1"
    - "Hub2"
    - "Lobby"
