name: ${project.artifactId}
main: ${project.groupId}.Main
version: ${project.version}
author: Dallen/Donovan Allen
depend: [Citizens]
load: STARTUP
commands:
  Kingdom:
    Desription: Base Kingdom command
    usage: /Kingdom <sub cmd>