name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}.Main
version: ${project.version}
author: Dallen/Donovan Allen
depend: [Citizens, ProtocolLib, BarAPI]
load: STARTUP
commands:
  Kingdom:
    description: Base Kingdom Command
    usage: |
            /Kingdom [Kingdom]
            /Kingdom found <name>
            /Kingdom online [Kingdom]
            /Kingdom list
            /Kingdom stats [Kingdom]
            /Kingdom edit [Kingdom]
            /Kingdom promote <player> [rank]
            /Kingdom announcements
            /Kingdom build [building name]
            /Kingdom demote <player> [rank]
            /Kingdom addnpc <name> <rank>
  Chat:
    description: Chat Handling Command
    usage: |
            /Chat
            /Chat <global|g|kingdom|k|party|p>
  Party:
    description: Party Command
    usage: |
            /Party
            /Party invite <player>
            /Party leave
            /Party kick <player>
            /Party join <player>
  mute:
    description: Used to mute a player from chat.
    usage: |
            /mute <player> [global|local]
  message:
    description: Used to private message a player
    aliases: msg
    usage: |
            /message <player> <chat>
  reply:
    description: Used to reply to a private message
    aliases: r
    usage: |
            /reply <chat>
  info:
    description: Get info about the server. Provides links to about pages.
    usage: |
            /info
  help:
    description: Gets help about how the server works. Provides links to help pages.
    aliases: [h, ?]
    usage: |
            /help
  list:
    description: Lists players in kingdom currently online.
    usage: |
            /list
  where:
    description: Gets the current location of the player.
    usage: |
            /where <player>
  ban:
    description: Bans a player on given mediums
    usage: |
            /ban <player> <reason> [network|website|all]
  unban:
    description: Unbans a player on the given mediums
    aliases: pardon
    usage: |
            /unban <player> [network|website|all]
  ipban:
    description: Ip bans a player's ip and the player if instructed.
    usage: |
            /ipban <player> [iponly]
  unipban:
    description: Unbans a player's ip and the player if instructed.
    aliases: ippardon
    usage: |
            /unipban <player> [iponly]
  kick:
    description: Kicks the player for the given reason.
    usage: |
            /kick <player> <reason>
  tmpban:
    description: Bans the player for the given time hh:mm:ss
    aliases: [tempban, temporaryban]
    usage: |
            /tmpban <player> <time|date>
  invspy:
    description: Allows the viewing (or editing) of a players inventory
    usage: |
            /invspy <player> [edit]
  fjail:
    description: Force jails a player
    usage: |
            /fjail <player> <reason> [time]
  vanish:
    description: poof
    aliases: v
    usage: |
            /vanish
  menu:
    description: opens the server main menu
    aliases: m
    usage: |
            /menu
            /menu textures
            /menu disconnect
            /menu serverSelect
            /menu connected
            /menu website
            /menu donate
            /menu vote
            /menu shop
            /menu ads
  self:
    description: gives stats about yourself
    usage: |
            /self
  uuid:
    description: gives player's uuid
    usage: |
            /uuid <player>
  crash:
    description: Crashes the player
    usage: |
            /crash <player> [style: 1|2]
  strack:
    description: stat tracker for admins of the server
    usage: |
            /strack load
            /strack mem
            /strack users
            /strack dbsize
            /strack newusers
            /strack kingdoms
            /strack covens
            /strack levels
            /strack dumpmem
            /strack errors
  broadcast:
    description: sends the given message to server/network (-n)
    aliases: b
    usage: |
            /broadcast [-n] <message>
  is:
    description: view info about ranks/players
    usage: |
            /is <player>
            /is <role>
  loadschem:
    description: moves schematics from World Edit to this plugin
    usage: |
           /loadschem
  fillplot:
    description: debug command
    usage: /<command>
  setskins:
    description: debug command
    usage: /<command>