name: Kingdoms
version: '${project.version}'
main: io.dallen.kingdoms.Kingdoms
api-version: '1.20'
commands:
  update:
    description: rebuild and reload the plugin
    usage: /update

  genworld:
    description: Generate new kingdoms world
    usage: /genworld
