name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}.Main
version: ${project.version}
author: Dallen/Donovan Allen
depend: [Citizens]
load: STARTUP
commands:
  Kingdom:
    Desription: Base Kingdom Command
    usage: |
            /Kingdom [Kingdom]
            /Kingdom found <name>
            /Kingdom online [Kingdom]
            /Kingdom list
            /Kingdom stats [Kingdom]
            /Kingdom edit [Kingdom]
            /Kingdom promote <player> [rank]
            /Kingdom announcements
            /Kingdom build [building name]
            /Kingdom demote <player> [rank]
            /Kingdom addnpc <name> <rank>
  Chat:
    Desription: Chat Handling Command
    usage: |
            /Chat
            /Chat <global|g|kingdom|k|party|p>
  Party:
    Desription: Party Command
    usage: |
            /Party
            /Party invite <player>
            /Party leave
            /Party kick <player>
            /Party join <player>
  mute:
    Desription: Used to mute a player from chat
    usage: |
            /mute <player> [global]