name: Kingdoms
version: '${project.version}'
main: io.dallen.kingdoms.Kingdoms
api-version: '1.20'
depend: [Citizens, ProtocolLib, WorldEdit]
commands:
  update:
    description: rebuild and reload the plugin
    usage: /update

  genworld:
    description: Generate new kingdoms world
    usage: /genworld

  cleardata:
    description: Remove all kingdoms data
    usage: /cleardata

  test:
    description: Test something
    usage: /test

